### PR TITLE
Add DNS dialog to 'manage names' page

### PR DESCRIPTION
**Pull request by neurocod**
It alows to format DNS records to insert it into NVS page. Also, some signals&slots connections in GUI now use function-pointer `QObject::connect` instead of string versions - which is now more type-safe at compile time.
image
image
image
image

### CODE REVIEW

**Comment by braiden-vasco** [comment]
Very useful feature!

**Comment by neurocod** [comment]
As teamlead wished, now DNS page became a popul dialog inside 'Manage names' page. Pull request is updated.
image

**Comment by neurocod** [comment]
placeholder text changed to tooltip and "(?)" mark:
image

**Comment by EvgenijM86** [comment]
Why did you move some functions to display/use wallet outside #ifdef ENABLE_WALLET? For example:
```
-    /* Switch to receive coins page /
-    void gotoReceiveCoinsPage();
```

**Pull request merged**
